---
python_deploy__type: 'git_without_setup'
python_deploy__name: '{{ test__app_name }}'
python_deploy__version: '{{ test__version }}'

python_deploy__user: '{{ test__user }}'
python_deploy__group: '{{ test__group }}'

python_deploy__dependent_apt_packages:
  - '{{ test__python_deploy__dependent_apt_packages }}'
python_deploy__dependent_services:
  - '{{ test__python_deploy__dependent_services }}'

python_deploy__requirements_files: '{{ test__requirements_files }}'
python_deploy__upgrade_pip: True

python_deploy__python: '{{ test__python }}'
python_deploy__path_root: '{{ ansible_local.fhs.app + "/" + test__app_name }}'
python_deploy__path_app: '{{ test__path_app }}'

python_deploy__git_service_host: 'github.com'
python_deploy__git_service_account: 'rybakm'
python_deploy__git_service_repo: 'ansible-python_deploy-test_without_setup'
python_deploy__git_service_access_token: None
