---
test__python_deploy__dependent_apt_packages:
  - name: 'libssl-dev'
  - name: 'curl'
  - name: 'procps'

test__python_deploy__dependent_services:
  - name: 'test-webserver'
    decription: 'Test webserver'
    state: 'present'
    type: 'poetry'
    command: 'gunicorn'
    command_options:
      - '-c gunicorn.conf.py'
      - 'wsgi:app'
    working_directory: '{{ test__path_app }}'
